export {MainLayout} from './Layout';
export {SkeltonPage} from './SkeltonPage';
export {SkeltonDashboardPage} from './SkeltonPage';
export {SkeltonPageForTable} from './SkeltonPage'
export {SkeltonTabsWithThumbnail} from './SkeltonPage'
export {SkeltonTabsLayoutFull} from './SkeltonPage'
export {SkeltonPageForProductDetail} from './SkeltonPage'
export {SkeltonTabsLayoutSecondary} from './SkeltonPage'
export {SkeltonPageWithTabs} from './SkeltonPage'
export {SkeltonPaymentPage} from './SkeltonPage'
export {SkeltonShippingPage} from './SkeltonPage'
export * from '../Utils/index';